include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - avoid_print
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_lambdas
    - prefer_relative_imports

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
