const fs = require('fs');
const path = require('path');

function generateLocales() {
  const localesDir = path.join(__dirname, '../core-data/localization');
  const files = fs.readdirSync(localesDir).filter(f => f.endsWith('.json'));

  const localeData = {};
  for (const file of files) {
    const locale = file.replace('.json', '');
    const content = fs.readFileSync(path.join(localesDir, file), 'utf8');
    localeData[locale] = JSON.parse(content);
  }

  // 1. Generate JS/TS Locale Data
  const tsContent = `/**
 * Auto-generated localization data.
 * Do not edit this file directly. 
 * Edit files in core-data/localization instead, then run build-locales.js.
 */

export const LOCALE_DATA: Record<string, Record<string, any>> = ${JSON.stringify(localeData, null, 2)};

export const SUPPORTED_LOCALES = Object.keys(LOCALE_DATA);
`;
  const tsDest = path.join(__dirname, '../packages/zodiac-js/src/localization/locale-data.ts');
  fs.mkdirSync(path.dirname(tsDest), { recursive: true });
  fs.writeFileSync(tsDest, tsContent, 'utf8');

  // 2. Generate Dart Locale Data
  let dartMapStr = '{\n';
  for (const [locale, data] of Object.entries(localeData)) {
    dartMapStr += `  '${locale}': {\n`;
    for (const [k, v] of Object.entries(data)) {
      if (Array.isArray(v)) {
        const arrStr = v.map(item => `'${item.replace(/'/g, "\\'")}'`).join(', ');
        dartMapStr += `    '${k}': const <String>[${arrStr}],\n`;
      } else {
        dartMapStr += `    '${k}': '${v.replace(/'/g, "\\'").replace(/\n/g, '\\n')}',\n`;
      }
    }
    dartMapStr += `  },\n`;
  }
  dartMapStr += '}';

  const dartContent = `// Auto-generated localization data.
// Do not edit this file directly.
// Edit files in core-data/localization instead, then run scripts/build-locales.js.

const Map<String, Map<String, dynamic>> localeData = ${dartMapStr};

const List<String> supportedLocales = [${Object.keys(localeData).map(k => `'${k}'`).join(', ')}];
`;
  const dartDest = path.join(__dirname, '../packages/zodiac-dart/lib/src/localization/locale_data.dart');
  fs.mkdirSync(path.dirname(dartDest), { recursive: true });
  fs.writeFileSync(dartDest, dartContent, 'utf8');

  console.log('Successfully generated ' + tsDest);
  console.log('Successfully generated ' + dartDest);
}

generateLocales();
